spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
#    url: jdbc:h2:mem:testdb
#    username: test
#    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
#  packages-to-scan: com.jieun.shop.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  use-fqn: true