spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
#    url: jdbc:h2:mem:testdb
#    username: test
#    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console